/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppButton {
        "disabled": boolean;
        "element": string;
    }
    interface AppPageAbout {
    }
    interface AppPagePkmn {
        "nice": string;
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppButtonElement extends Components.AppButton, HTMLStencilElement {
    }
    var HTMLAppButtonElement: {
        prototype: HTMLAppButtonElement;
        new (): HTMLAppButtonElement;
    };
    interface HTMLAppPageAboutElement extends Components.AppPageAbout, HTMLStencilElement {
    }
    var HTMLAppPageAboutElement: {
        prototype: HTMLAppPageAboutElement;
        new (): HTMLAppPageAboutElement;
    };
    interface HTMLAppPagePkmnElement extends Components.AppPagePkmn, HTMLStencilElement {
    }
    var HTMLAppPagePkmnElement: {
        prototype: HTMLAppPagePkmnElement;
        new (): HTMLAppPagePkmnElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-button": HTMLAppButtonElement;
        "app-page-about": HTMLAppPageAboutElement;
        "app-page-pkmn": HTMLAppPagePkmnElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppButton {
        "disabled"?: boolean;
        "element"?: string;
    }
    interface AppPageAbout {
    }
    interface AppPagePkmn {
        "nice"?: string;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-button": AppButton;
        "app-page-about": AppPageAbout;
        "app-page-pkmn": AppPagePkmn;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-button": LocalJSX.AppButton & JSXBase.HTMLAttributes<HTMLAppButtonElement>;
            "app-page-about": LocalJSX.AppPageAbout & JSXBase.HTMLAttributes<HTMLAppPageAboutElement>;
            "app-page-pkmn": LocalJSX.AppPagePkmn & JSXBase.HTMLAttributes<HTMLAppPagePkmnElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
